name: Install Ansible and Dependencies

on: [push]

jobs:
  setup-ansible-tools:
    runs-on: ubuntu-24.04 # Specifies Ubuntu 20.x as the runner

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Ensures the latest version of Python 3 is used

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible==2.10.7  # Installs Ansible and its dependencies
    - name: Verify Installation
      run: |
        ansible --version  # Check Ansible version
        ansible-galaxy --version # Check Ansible Galaxy version
        ansible-vault --version  # Check Ansible Vault version
        ansible-galaxy --help  # Verify Ansible Galaxy command is available
        ansible-vault --help  # Verify Ansible Vault command is available
